#!/bin/sh

# Get the package destination.
eval $(env | grep "^SYNOPKG_PKGDEST=")

# Give user execution permissions to all those admin users.
chmod u+x $SYNOPKG_PKGDEST/apps/*.cgi
chmod u+x $SYNOPKG_PKGDEST/apps/*/*.cgi
chmod u+x $SYNOPKG_PKGDEST/apps/*/*/*.cgi
chmod u+x $SYNOPKG_PKGDEST/apps/*/*/*/*.cgi

# Create a folder for the git repos.
mkdir /volume1/git

exit 0
