#!/bin/sh

case $1 in
	start)
		# Create a symlink to the git repos.
		ln -s /volume1/git /git
		exit 0
	;;
	stop)
		exit 0
	;;
	status)
		exit 0
	;;
	log)
		echo "Git Server Plus is installed properly. To access it, select it from the Main Menu">/tmp/cc.log
		echo "/tmp/cc.log";
		exit 0
	;;
esac
